var GAME_LEVELS = [
  ["!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!xxxxxxxxxx!!",
   "                                                                  xvx        x!!",
   "                                                                             x!!",
   "                                                           o  o  o   o       x!!",
   "                                               o o                           x!!",
   "                                                         xxxxxxxxxx!xxxxx xxxx!!",
   "                                    o o       rrrrr              x!!!x       x!!",
   "o                                                                xx!xx   o   x!!",
   "                                   rrrrr                          xvx    o   x!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                       rr                     x!!",
   "                                          o o                                x!!",
   "                                                                             x!!",
   "                                          rrr                                x!!",
   " o | | | | |L                                                                x!!",
   "                 @            x                                  xxxxx      yx!!",
   " xxxxxxxxxxxxxxxxxxxxxxxx   sxx           o o              xxxxxxx   xxxxoxxxx!!",
   "                           sx x    r                rr     x            x x  x!!",
   "                          sx  x!!!!!     xxxxx      !!!!!!!x            xox  x!!",
   "                         sx   x!!!x!       =        !x!!!!!x            x x  x!!",
   "                        sx    xxxxx!                !xxxxxxx            x x  x!!",
   "xxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x x!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x x!!!!!"],
  ["xxxxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "      x x                                                                             ",
   "      x x                                                                             ",
   "                       o    o              o    o                                     ",
   "=             L                                                            o       o= ",
   "                                                                                      ",
   "xxxxxxxsxxxxxxxxxxxxxxxssssssxxxxxxxxxxxxxxssssssxxxxxxxxxxxxxxxxxxxxxxxxxxxsss xxxxxx",
   "xxx|xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx xxxxxx",
   "   |                                                                                  ",
   "                               ooo                                                    ",
   "                                      ooo                                            |",
   "                                                                                    | ",
   "                                     rrrrr      ooo                                |  ",
   "                                                                                  |   ",
   "                                               rrrrr                             |    ",
   "  x|    =  =           ooo                                              L =   = |    o",
   "  x|                                                                                  ",
   "@ xxssssxxxxxxxxxxxxsssxxxsssxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "o xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x                                                                                   ",
   "  x=         =                                                                      = ",
   "  x         x                         x!!!!!!!!!!!!!!!!!!!!!!!x                      o",
   "  x!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxvxxxvxxxxxvxxxvxvxvxvxvxxxxxxxxxxxxxxxxxxxxx   ",
   "  x!!!!!!!xv                                                                         x",
   "  x!!!!!!!x                                                                         xx",
   "  xxxxxxxxx                                                                        xxx",
   "                                                    L            o  o  o  o  o    xxxx",
   "                                                                                 xxxxx",
   "ssxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],
  ["xxxxxvvvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "         xx                                                                                         ",
   "  @      xx                              xxxxxxxxxxxxxxxxxxx                                        ",
   " xxx     xx                            xxx                 xxx                                      ",
   "  xx     xx                          xxx                     xxx                                    ",
   "  xx     xx                    orrrxxx                         xxxrr                                ",
   "x xx    oxx                 orrrrrrxxx  xx                 xx  xxxr                                 ",
   "  xx    xxx               orrrrrrrrxxx  x!!x             x!!x  xxxr                                 ",
   " oxx     xx              orrrrrrrrrxxx   x!!!x         x!!!x   xxxr                 rrr             ",
   " xxx     xx             orrrrrrrrrrxxx    x!!!!x     x!!!!x    xxxrr               rrrrrr           ",
   "  xxo    xx             rrrrrrrr    xxx    xxxxxx   xxxxxx    xxx                  rrrrrrr          ",
   "  xxx    xx             rrrrrrr      xxx         xxx         xxx                   rrrrrrrr         ",
   "x xx     xx             rrrrrrr       xxx       x!!!x       xxx                     rrrrrrrr        ",
   "  xx     xx         o    rrrrr        xxx!     x!!x!!x     !xxx                       rrrrrrr       ",
   "  xx     xx     xxxxxxxxx rrrr        xxx!!!!!!!xx!xx!!!!!!!xxx                        rrrrrr       ",
   " xxx    oxx                rrr         xxvxvxvxvxxxxxvxvxvxvxx           oo            rrrrrr       ",
   "  xx    xxx                 rrr                   oo                    oooo            rrrrr       ",
   "o xx     xxx                 rr                                        oooooo           rrrr        ",
   "x xx     xx                   r                                       oooooooo          rrr         ",
   "           L                                                         oooooooooo        rrr          ",
   "                                                                    oooooooooooo      rr            ",
   "xxxxxxxxxxxxxxxx|       |xxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   " =             =              =                 =    =                 =                          = ",
   "                  |   |                                                                             ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                     ",
   "                                                     ",
   "                                                     ",
   "    o   o           o             o  o               ",
   "     o o oo  o   o   o     o     o     o o o         ",
   "      o o  o o   o    o   o o   o    o o     o       ",
   "      o o  o o   o     o o   o o     o o     o       ",
   " @    o  oo   ooo       o     o      o o     o       ",
   "                                                     ",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;